config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes do
    resources :doses, only: [:new, :create, :edit]
    resources :reviews, only: [:new, :create]
  end
  resources :users, except: [ :index, :destroy ]
  resources :ingredients
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
  belongs_to :user
  validates :recipe, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :user
  has_many :doses
  has_many :recipes, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  validates :content, presence: true, length: { minimum: 5, maximum: 100 }
  validates :rating, presence: true, inclusion: (1..5)

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :doses
  has_many :ingredients
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    attributes = [:username, :first_name, :last_name, :email]
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @dose = Dose.new
    authorize @dose
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @dose = Dose.new(dose_params.merge(user:current_user))
    authorize @dose
    @dose.recipe = @recipe

    if @dose.save
      redirect_to recipe_path(@recipe)
    else
      @dose= Dose.new
      flash[:notice] = "The creation could not be completed."
      render "recipes/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to recipe_path(@dose.recipe)
    authorize @dose
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = policy_scope(Ingredient).order(name: :asc)
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
    authorize @ingredient
  end

  def create
    @ingredient = Ingredient.new(ingredient_params.merge(user:current_user))
    authorize @ingredient
    if @ingredient.save
      redirect_to ingredients_path
      flash[:notice] = "Ingredient was successfully created."
    else
      render 'new'
      flash[:notice] = "The creation could not be completed."
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
    authorize @ingredient
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.user = current_user
    @ingredient.update(ingredient_params)
    authorize @ingredient
    if @ingredient.save
      redirect_to ingredients_path
    else
      render :new
      flash[:notice] = "The modification could not be completed."

    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    authorize @ingredient

    redirect_to ingredients_path
    flash[:notice] = "Ingredient was successfully deleted."
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @recipes = Recipe.all
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    if params[:query].present?
      sql_query = " \
        recipes.name ILIKE :query \
        OR recipes.description ILIKE :query \
      "
      @recipes = policy_scope(Recipe).where(sql_query, query: "%#{params[:query]}%")
    else
      @recipes = policy_scope(Recipe)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @average = @recipe.reviews.map(&:rating).sum / @recipe.reviews.count.to_f
    authorize @recipe
  end

  def new
    @recipe = Recipe.new
    authorize @recipe
  end

  def create
    @recipe = Recipe.new(recipe_params.merge(user:current_user))
    @recipe.user = current_user
    authorize @recipe
    if @recipe.save
      redirect_to recipe_path(@recipe)
      flash[:notice] = "Recipe was successfully created."
    else
      render 'new'
      flash[:notice] = "The creation could not be completed."
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    authorize @recipe
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.user = current_user
    @recipe.update(recipe_params)
    authorize @recipe
    if @recipe.save
      redirect_to recipe_path(@recipe)
      flash[:notice] = "Recipe was successfully updated."
    else
      render :new
      flash[:notice] = "The modification could not be completed."

    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    authorize @recipe

    redirect_to recipes_path
    flash[:notice] = "Recipe was successfully deleted."
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :photo, :dairyfree, :eggfree, :vegan)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @review = Review.find(:id)
    authorize @review
  end

  def new
    # we need @restaurant in our `simple_form_for`
    @recipe = Recipe.find(params[:recipe_id])
    @review = Review.new
    authorize @review
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @review = Review.new(review_params)
    authorize @review
    @review.recipe = @recipe
    @review.user = current_user
    if @review.save
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    authorize @review
    redirect_to recipe_path(@review.recipe)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      flash[:alert] = "Your profile has been successfully updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :last_name, :first_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doses/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="my-4">Ajoutez un ingrédient à votre recette</h1>

      <%= simple_form_for [@recipe, @dose] do |f| %>
        <%= f.input :description, label: 'Dose' %>
        <%= f.association :ingredient, collection: Ingredient.order('name ASC'), label: 'Ingrédient' %>
        <div class="button-container">
          <%= f.button :submit, 'Ajouter', class: 'pink-button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="my-4">Créez un nouvel ingrédient</h1>
      <%= simple_form_for @ingredient do |f| %>
        <%= f.input :name, label: "Nom de l'ingrédient"  %>
        <%= f.input :description %>
        <div class="button-container">
          <%= f.button :submit,"Modifiez l'ingrédient", class: 'pink-button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/index.html.erb
<div class=image-main  style="background-image:linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://cdn.dribbble.com/users/2536875/screenshots/12017195/media/cdbaa929738cc6183c1a2c0ef7057539.jpeg);">

</div>

<div class="title-grid">
  <div class="ingredients-title ">Petit index de bons produits sans gluten</div>
  <h2 class="ingredients-subtitle">"C'est avec les meilleurs ingrédients que l'on fait les meilleures recettes"</h2>
</div>

<div class="container-recipe">
  <ul>
    <% @ingredients.each do |ingredient| %>
      <li><%= ingredient.name.capitalize %>
        <% if policy(ingredient).edit? %>
          <%= link_to edit_ingredient_path(ingredient) do%>
            <i id="black-ud-icon" class="fas fa-edit ml-3"></i>
          <% end %>
        <% end %>
        <% if policy(ingredient).destroy? %>
          <%= link_to ingredient_path(ingredient), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i id="black-ud-icon" class="fa fa-trash destroy_dose"></i>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <p>
    <%=link_to new_ingredient_path do %>
    <span class="add-recipe">
      <i class="fas fa-plus mr-1">
      </i>
      Ajoutez un ingrédient
    </span>
    <% end %>
  </p>
</div>

app/views/ingredients/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="my-4">Modifiez l'ingrédient</h1>

      <%= simple_form_for @ingredient do |f| %>
        <%= f.input :name, label: "Nom de l'ingrédient" %>
        <%= f.input :description %>
        <div class="button-container">
          <%= f.button :submit,"Ajoutez un nouvel ingrédient", class: 'pink-button' %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Glutenfreeplease</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= favicon_link_tag asset_path('cookie.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="content-wrapper">
      <%= yield %>
    </div>


    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-banner" style="background-image:linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0.2)), url(https://cdn.dribbble.com/users/1426840/screenshots/12019984/media/e57f7d19d88e91f22f9944f86804e20e.png);">

    <div class="discover-recipes-card">
      <div class="discover-recipes-content">
        <h1>"Parce que <strong class="pink-text">Sans Gluten</strong>
        <br> rime aussi avec <strong class="pink-text">Gourmandise</strong> !"
        </h1>
      </div>
    </div>

    <div>
      <%= link_to "Découvrez nos recettes", recipes_path, class: "pink-button"%>
    </div>

</div>


  <!-- pictures -->

<div class="container-fluid" style="position:relative;">
  <div class="row">
    <div class="col">
      <h2 class="index-title">Profitez du confinement pour cuisiner!!!</h2>

    <div class="cards-grid">
      <% @recipes.first(3).each do |recipe| %>
        <%= link_to recipe_path(recipe) do %>
          <% if recipe.photo.attached?%>
            <div class ="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path recipe.photo.key %>')">
          <% else %>
            <div class ="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1515192088926-be05d2dded88?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1652&q=80')">
          <% end %>
              <h2 class="card-title"><%= recipe.name.capitalize %> </h2>
              <div class="diet-icon-container">
                <% if recipe.dairyfree %>
                  <%= image_tag("dairyfree.png", :class => " diet-icon-index")%>
                <% else %>
                <% end %>
                <% if recipe.eggfree %>
                  <%= image_tag("eggfree.png", :class => " diet-icon-index")%>
                <% else %>
                <% end %>
                <% if recipe.vegan %>
                  <%= image_tag("vegan.png", :class => " diet-icon-index")%>
                <% else %>
                <% end %>
              </div>
            </div>
        <% end %>
      <% end %>
    </div>

    </div>
  </div>
  <div>
    <div class="col d-flex justify-content-center mt-4 mb-4">
      <%= link_to "Pour découvrir encore plus de recettes, c'est par ici!", recipes_path, class:"small-pink-button" %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="my-4">Modifiez votre recette</h1>

      <%= simple_form_for @recipe do |f| %>
        <%= f.input :name, label: 'Nom de la recette' %>
        <%= f.input :description, label: 'Description de la préparation' %>
        <%= f.input :dairyfree, :as => :boolean, input_html: {checked: false}, label: "Sans laitage d'origine animale" %>
        <%= f.input :eggfree, :as => :boolean, input_html: {checked: false}, label: "Sans oeuf" %>
        <%= f.input :vegan, :as => :boolean, input_html: {checked: false}, label: "Vegan" %>
        <%= f.input :photo, as: :file %>
        <div class="button-container">
          <%= f.button :submit,'Modifiez votre recette', class: 'pink-button' %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class=image-main-recipes  style="background-image:linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://cdn.dribbble.com/users/4712379/screenshots/12064153/media/9a3dc130366a2cb0784900f3a916467c.png);">
</div>

<div class="title-grid">
  <h2 class="index-title">Découvrez nos recettes sans gluten</h2>
  <!-- searchbar-->
  <div>
    <% if current_page?('/') %>
    <% else %>
    <div class="form-group index-searchbar">
        <div>
          <%= form_tag recipes_path, method: :get do %>
          <%= text_field_tag :query,params[:query],class: "form-control form-frame",
            placeholder: "Je cherche..."%>
        </div>
        <div>
          <%= submit_tag "➔", class: "small-pink-button-searchbar" %>
        </div>
        <% end %>
    </div>

  <% end %>
  </div>

</div>

<div class="container-recipe">
  <div class="cards-grid">
    <% @recipes.each do |recipe|%>
      <%= link_to recipe_path(recipe) do %>
        <% if recipe.photo.attached? %>
        <div class ="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path recipe.photo.key %>')">
        <% else %>
        <div class ="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1515192088926-be05d2dded88?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1652&q=80')">
        <% end %>
          <div class="card-title">
            <%=recipe.name.capitalize%>
          </div>

          <div class="card-stars">
            <div class=''>
              <% if recipe.reviews.empty? %>
                <% else %>
                  <% if !@average.nil? %>
                    <%= icon('fas', 'star', class: 'star-rating') * (@average) %>
                    <% if @average.round != @average  %>
                      <%= icon('fas', 'star-half-alt', class: 'star-rating margin-half-star') %>
                    <% end %>
                    <%= icon('far', 'star', class: 'star-rating') * (5 - @average) %>
                  <% end %>
              <% end %>
            </div>

          </div>

          <div class="diet-icon-container">
            <% if recipe.dairyfree %>
              <%= image_tag("dairyfree.png", :class => " diet-icon-index")%>
            <% else %>
            <% end %>
            <% if recipe.eggfree %>
              <%= image_tag("eggfree.png", :class => " diet-icon-index")%>
            <% else %>
            <% end %>
            <% if recipe.vegan %>
              <%= image_tag("vegan.png", :class => " diet-icon-index")%>
            <% else %>
            <% end %>
          </div>

          </div>
      <% end %>
    <% end %>

    <div class="card-container">
      <% if policy(Recipe).create? %>
        <%= link_to new_recipe_path do %>
          <div class="round-card" style="background-image:linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://i.pinimg.com/474x/80/46/1a/80461a2037fae3da6c425c821c4eec3e.jpg);">
            <div class="card-title-add">+ votre recette</div>
          </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="my-4">Créez une nouvelle recette</h1>

      <%= simple_form_for @recipe do |f| %>
        <%= f.input :name, label: 'Nom de la recette' %>
        <%= f.input :description, label: 'Description de la préparation' %>
        <%= f.input :dairyfree, :as => :boolean, input_html: {checked: false}, label: "Sans laitage d'origine animale" %>
        <%= f.input :eggfree, :as => :boolean, input_html: {checked: false}, label: "Sans oeuf" %>
        <%= f.input :vegan, :as => :boolean, input_html: {checked: false}, label: "Vegan" %>
        <%= f.input :photo, as: :file %>
        <div class="button-container">
          <%= f.button :submit,'Créez votre recette', class: 'pink-button' %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<% if @recipe.photo.attached?%>
  <div id="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)),
    url('<%= cl_image_path @recipe.photo.key, crop: :fill %>')">
<% else %>
  <div id="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1515192088926-be05d2dded88?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1652&q=80/?recipe-<%=@recipe.name%>')" >
<% end %>
  <div class="recipe-items">
    <div class="recipe-information">
      <div class="recipe-title-container">
        <div class="recipe-title"><%= @recipe.name.capitalize %>
        </div>


          <div class="edit-delete">
            <% if policy(@recipe).edit? %>
              <%= link_to edit_recipe_path(@recipe) do%>
                <i id="show-icon" class="fas fa-edit"></i>
              <% end %>
            <% end %>
            <% if policy(@recipe).destroy? %>
              <%= link_to recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i id="show-icon" class="fa fa-trash destroy_dose"></i>
              <% end %>
            <% end %>
          </div>

      </div>
      <div class='star-recipe-information'>
        <% if @recipe.reviews.empty? %>
        <% else %>
          <% if !@average.nil? %>
            <%= icon('fas', 'star', class: 'star-rating') * (@average) %>
            <% if @average.round != @average  %>
              <%= icon('fas', 'star-half-alt', class: 'star-rating margin-half-star') %>
            <% end %>
            <%= icon('far', 'star', class: 'star-rating') * (5 - @average) %>
          <% end %>
        <% end %>
      </div>
      <div class='diet-recipe-information'>
        <% if @recipe.dairyfree %>
          <%= image_tag("dairyfree.png", :class => "mr-3 diet-recipe-information")%>
          <% else %>
        <% end %>
        <% if @recipe.eggfree %>
          <%= image_tag("eggfree.png", :class => "mr-3 diet-recipe-information")%>
          <% else %>
        <% end %>
        <% if @recipe.vegan %>
          <%= image_tag("vegan.png", :class => "mr-3 diet-recipe-information")%>
          <% else %>
        <% end %>
      </div>



      </div>
    </div>
  </div>
  <div class="recipe-elements-container">
    <div class="recipe-ingredients">
    <div class="ingredient-title">
      Ingrédients
    </div>
    <div>
        <ul>
          <% @recipe.doses.each do |dose| %>
            <li><%= dose.ingredient.name.capitalize %> : <%= dose.description %>
              <% if policy(dose).destroy? %>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i id="show-icon"  class="fa fa-trash destroy_dose ml-3"></i>
              <% end %>
            <% end %>
            </li>
          <% end %>
        </ul>
    </div>
    <div>
      <% if @recipe.user == current_user %>
        <%= link_to new_recipe_dose_path(@recipe) do %>
          <div class="add-recipe">
            <i class="fas fa-plus mr-2"></i>
            Ajouter un ingrédient à la recette
          </div>
        <% end %>
      <% end %>
    </div>
    <p></p>

  </div>

  <div class="preparation">
    <h3 class="recipe-category-title">Préparation</h3>

    <ol class="recipe-description">
      <% @recipe.description.split(".").each do |line| %>
        <li class="recipe-steps">
          <%= line %>.
        </li>

      <% end %>
    </ol>



  </div>

  <div class="review">
    <h3 class="recipe-category-title">Qu'avez-vous pensé de cette recette de <%=@recipe.name.downcase %>?</h3>

    <% if @recipe.reviews.empty? %>
      <p>Soyez le premier à donner votre avis sur cette recette</p>
    <% else %>
      <ul class="list-group">
        <% @recipe.reviews.each do |review| %>

          <li class="review-box">
            <div class="review-rating-comments"><%= icon('fas', 'star', class: 'star-rating') * (review.rating) %><%= icon('far', 'star', class: 'star-rating') * (5 - review.rating) %>
            -  <%= review.content %>
            </div>
            <div class="review-user">
              <div ><%= review.user.username %></div>
              <% if policy(review).destroy? %>
                <div><%= link_to review_path(review), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i id="black-ud-icon" class="fa fa-trash destroy_dose ml-3 "></i></div>
              <% end %>
            </div>

            <% end %>
          </li>
        <% end %>

      </ul>
        <% end %>

    <div>
      <%= link_to new_recipe_review_path(@recipe) do %>
        <div class="add-recipe mt-3"><i class="fas fa-plus mr-1"></i>
          Partagez avec nous votre avis sur cette recette!
        </div>
      <% end %>
    </div>

  </div>

  </div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="bg-white p-4 my-4">
    <div class="col-xs-4" id="form">
      <h1>Comment avez-vous trouvé cette recette de <%= @recipe.name %>?</h1>
      <%= simple_form_for [@recipe, @review] do |f| %>
        <%= f.input :content, label: "Vos commentaires"%>
        <%= f.input :rating, collection: (1..5).to_a, label: "Notez cette recette" %>
        <%= f.submit "Partagez votre avis", class: "small-pink-button" %>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/users/_about_user.html.erb
<div class="bg-white p-3 my-3" id="about-me">
  <div class="d-flex justify-content-between align-items-baseline">
    <h2 class="mb-3">Mon profil</h2>
    <% unless current_page?(edit_user_url) %>
      <span class="pink-btn-edit" class="btn "><%= link_to "Editer mon profil", edit_user_url %></span>
    <% end %>
  </div>
  <% if current_page?(edit_user_url) %>
    <%= simple_form_for(@user) do |f| %>
      <div class="mb-3">
        <span class="pink-badge">Email</span> <span class="text-muted"><%= @user.email %></span>
      </div>
      <%= f.input :username, label:"Nom utilisateur" %>
      <%= f.input :first_name, label:"Prénom" %>
      <%= f.input :last_name, label:"Nom" %>
      <%= f.button :submit, "Mettre à jour mon profil", class: 'pink-btn-edit' %>
    <% end %>
  <% else %>
    <div>
      <ul class="list-unstyled">
        <li class="d-flex align-items-center"><i class="fas fa-user icon-user-profile"></i><%= @user.username %></li>
        <li class="d-flex align-items-center"><i class="far fa-envelope icon-user-profile"></i><%= @user.email %></li>
        <li class="d-flex align-items-center"><i class="far fa-id-badge icon-user-profile"></i><%= "#{@user.first_name} #{@user.last_name}" %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/users/_recipes.html.erb
<div class="bg-white p-3 my-3">
  <h2 class="mb-3 ml-3">Mes recettes</h2>
  <div class="cards-recipe">
    <% @user.recipes.each do |recipe| %>
    <div class="card-recipe">
      <div class="card-booking-infos">
        <div class="d-flex align-items-baseline">
          <h3><%= recipe.name.capitalize %></h3>
          <div class="edit-delete">
              <%= link_to edit_recipe_path(recipe) do%>
                <i id="black-ud-icon" class="fas fa-edit ml-3"></i>
              <% end %>
              <%= link_to recipe_path(recipe), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i id="black-ud-icon" class="fa fa-trash destroy_dose"></i>
              <% end %>
          </div>
        </div>
        <ul class="list-unstyled">
          <% if recipe.description.nil? %>
            <li><span class="pink-badge">Description</span> <%= recipe.description %></li>
          <% else %>
            <li><span class="pink-badge">Description</span> <%= "#{recipe.description.split(".").first}..." %></li>
          <% end  %>
        </ul>
      </div>
    </div>
  <% end %>
  </div>


</div>